import { del, head } from "@vercel/blob";
import { and, eq, max } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import { getDb } from "@/db";
import { auditEvents, courtPhotos, courts, merchants, sitePhotos, sites } from "@/db/schema";
import { requirePlatformAdmin } from "@/lib/auth/access";

export const runtime = "nodejs"; const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i; const TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
export async function POST(request: Request) {
  if (request.headers.get("origin") !== new URL(request.url).origin) return NextResponse.json({ error: "Invalid request origin." }, { status: 403 }); const admin = await requirePlatformAdmin();
  const body = await request.json().catch(() => null) as null | { merchantId?: string; kind?: string; targetId?: string; mediaId?: string; altText?: string; pathname?: string }; const merchantId = body?.merchantId ?? ""; const kind = body?.kind ?? ""; const targetId = body?.targetId ?? ""; const mediaId = body?.mediaId ?? ""; const pathname = body?.pathname ?? ""; const altText = String(body?.altText ?? "").trim(); const entity = targetId || merchantId;
  if (!UUID.test(merchantId) || !UUID.test(mediaId) || !["logo", "cover", "site", "court"].includes(kind) || !pathname.startsWith(`admin-media/${merchantId}/${kind}/${entity}/${mediaId}.`) || altText.length > 200) return NextResponse.json({ error: "Invalid image details." }, { status: 400 });
  const blob = await head(pathname).catch(() => null); if (!blob || blob.size > 8 * 1024 * 1024 || !TYPES.has(blob.contentType)) return NextResponse.json({ error: "The uploaded file is not a supported image." }, { status: 400 });
  const db = getDb(); const [merchant] = await db.select({ id: merchants.id, slug: merchants.slug, oldPathname: kind === "logo" ? merchants.logoPathname : merchants.coverPathname }).from(merchants).where(eq(merchants.id, merchantId)).limit(1); if (!merchant) return NextResponse.json({ error: "Merchant not found." }, { status: 404 });
  const url = kind === "logo" || kind === "cover" ? `/api/merchant-media/${kind}/${merchantId}?v=${mediaId}` : `/api/venue-photos/${kind}/${mediaId}`;
  try {
    if (kind === "logo" || kind === "cover") await db.batch([db.update(merchants).set(kind === "logo" ? { logoUrl: url, logoPathname: pathname, updatedAt: new Date() } : { coverUrl: url, coverPathname: pathname, updatedAt: new Date() }).where(eq(merchants.id, merchantId)), db.insert(auditEvents).values({ merchantId, actorUserId: admin.id, action: `platform.merchant.${kind}_overridden`, targetType: "merchant", targetId: merchantId, after: { pathname } })]);
    else if (kind === "site") { const [site] = await db.select({ id: sites.id }).from(sites).where(and(eq(sites.id, targetId), eq(sites.merchantId, merchantId))).limit(1); if (!site) throw new Error("Site not found"); const [{ order }] = await db.select({ order: max(sitePhotos.sortOrder) }).from(sitePhotos).where(eq(sitePhotos.siteId, targetId)); await db.batch([db.update(sitePhotos).set({ isCover: false }).where(eq(sitePhotos.siteId, targetId)), db.insert(sitePhotos).values({ id: mediaId, merchantId, siteId: targetId, url, pathname, altText: altText || null, isCover: true, sortOrder: (order ?? -1) + 1, createdByUserId: admin.id }), db.insert(auditEvents).values({ merchantId, actorUserId: admin.id, action: "platform.site.photo_overridden", targetType: "site", targetId, after: { pathname } })]); }
    else { const [court] = await db.select({ id: courts.id }).from(courts).where(and(eq(courts.id, targetId), eq(courts.merchantId, merchantId))).limit(1); if (!court) throw new Error("Court not found"); const [{ order }] = await db.select({ order: max(courtPhotos.sortOrder) }).from(courtPhotos).where(eq(courtPhotos.courtId, targetId)); await db.batch([db.update(courtPhotos).set({ isCover: false }).where(eq(courtPhotos.courtId, targetId)), db.insert(courtPhotos).values({ id: mediaId, merchantId, courtId: targetId, url, pathname, altText: altText || null, isCover: true, sortOrder: (order ?? -1) + 1, createdByUserId: admin.id }), db.insert(auditEvents).values({ merchantId, actorUserId: admin.id, action: "platform.court.photo_overridden", targetType: "court", targetId, after: { pathname } })]); }
  } catch (error) { await del(pathname).catch(() => undefined); console.error("Admin media completion failed", error); return NextResponse.json({ error: "The image was uploaded but could not be saved." }, { status: 500 }); }
  if ((kind === "logo" || kind === "cover") && merchant.oldPathname && merchant.oldPathname !== pathname) await del(merchant.oldPathname).catch(() => undefined); revalidatePath(`/admin/merchants/${merchantId}`); revalidatePath(`/${merchant.slug}`); return NextResponse.json({ url });
}
